### ISSUE TITLE
Apk please

### ISSUE THREAD

**Issue by Kevinrop** [Arxk/TwitchCast#2]
When you upload the app to the playstore i cant download it, maybe u can give me a copy of the apk to intall it, I really want intall it so pleaseeeeeeee.

**Comment by Arxk** [comment]
Hi, You can use this while i fix this issue
    twitchcast-1.0.3-debug.apk
<https://docs.google.com/file/d/0B2JBNspfO2Nib2FFTTJqdE1jT1E/edit?usp=drivesdk>

**Comment by Arxk** [comment]
I'm sorry. This one is the correct APK
