### ISSUE TITLE
Feature Request: Ability to log in to get Sub-Only URL's

### ISSUE THREAD

**Issue by tarasis** [Arxk/TwitchCast#3]
Hi I love your project. Been using it to watch past Geek and Sundry broadcasts and have blogged about the project a couple of days ago. 

Unfortunately they have just made their past broadcasts and highlights subscription only. It would be useful if there was a way on a private installation of TwitchCast if you could log in to your twitch account, to get at those URL's. I would try and add it myself but I know nothing about web development.

**Comment by Arxk** [comment]
Hello, I've seen your blog post and i'm glad you liked it.
This is on my to-do list, but i'm lazy. Now that you asked I'll try...
regards.

2015-04-10 6:10 GMT-05:00 Robert McGovern <notifications@github.com>:

**Comment by tarasis** [comment]
Cheers Arxk, thanks for considering it. I would have emailed as you mention in the readme but I couldn't see an address.
